server:
  port: 9002

spring:
  application:
    name: content-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
